# Generated by Django 3.1.4 on 2021-01-07 16:09

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField(max_length=512)),
                ('requirements', models.TextField(max_length=512)),
                ('city', models.CharField(max_length=128)),
                ('state', models.CharField(max_length=128, null=True)),
                ('country', django_countries.fields.CountryField(max_length=2)),
            ],
        ),
    ]
