# Generated by Django 3.1.5 on 2021-01-17 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='years_worked',
            field=models.PositiveIntegerField(default=0, help_text='Years Worked'),
        ),
    ]
