# Generated by Django 3.1.4 on 2021-01-01 12:30

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField(max_length=512)),
                ('requirements', models.TextField(max_length=512)),
                ('city', models.CharField(max_length=128)),
                ('state', models.CharField(max_length=128, null=True)),
                ('country', django_countries.fields.CountryField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=128)),
                ('state', models.CharField(max_length=128, null=True)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('degree', models.CharField(choices=[('bsc', 'Bachelor of Science'), ('msc', 'Master of Science')], max_length=8)),
                ('major', models.CharField(choices=[('cmpe', 'Computer Engineering'), ('math', 'Mathematics')], max_length=8)),
                ('university', models.CharField(choices=[('itu', 'Istanbul Technical University'), ('boun', 'Bogazici University'), ('koc', 'Koc University')], max_length=8)),
                ('number_of_previous_work_experience', models.IntegerField(default=0)),
                ('years_worked', models.IntegerField(default=0)),
                ('is_currently_employed', models.BooleanField(default=False)),
                ('skills_text', models.TextField(max_length=512)),
            ],
        ),
    ]
