# Generated by Django 3.1.5 on 2021-01-16 17:42

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppliedJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_student_interested', models.IntegerField(choices=[(1, 'Student is interested with the job'), (0, 'Student is not interested with the job')], help_text='Recruiter Response')),
                ('recruiter_response', models.IntegerField(choices=[(0, 'No response from recruiter'), (1, 'Recruiter is interested with this student'), (2, 'Recruiter is not interested with this student')], default=0, help_text='Recruiter Response')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title', max_length=128)),
                ('description', models.TextField(help_text='Description', max_length=512)),
                ('requirements', models.TextField(help_text='Requirements', max_length=512)),
                ('city', models.CharField(help_text='City', max_length=128)),
                ('state', models.CharField(help_text='State', max_length=128, null=True)),
                ('country', django_countries.fields.CountryField(help_text='Country', max_length=2)),
            ],
        ),
    ]
