# Generated by Django 3.1.4 on 2021-01-18 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_auto_20210118_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedjob',
            name='match_rate',
            field=models.IntegerField(help_text='Match rate', null=True),
        ),
    ]
