# Generated by Django 3.1.5 on 2021-01-19 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_auto_20210119_0317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='requirements',
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(help_text='Description', max_length=1024),
        ),
    ]
