# Generated by Django 3.1.5 on 2021-01-19 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_auto_20210119_0325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(help_text='Description', max_length=5000),
        ),
    ]
