# Generated by Django 3.1.5 on 2021-01-19 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_auto_20210119_0332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='state',
            field=models.CharField(blank=True, help_text='State', max_length=128, null=True),
        ),
    ]
