# Generated by Django 3.1.5 on 2021-01-18 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiter',
            name='company_address',
            field=models.CharField(help_text='Company Address', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='company_name',
            field=models.CharField(help_text='Company Name', max_length=128, null=True),
        ),
    ]
