# Generated by Django 3.1.4 on 2021-01-07 14:55

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pladat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('pladatuser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pladat.pladatuser')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=128)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('address', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=128)),
                ('state', models.CharField(max_length=128, null=True)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('degree', models.CharField(choices=[('bsc', 'Bachelor of Science'), ('msc', 'Master of Science')], max_length=8)),
                ('major', models.CharField(choices=[('cmpe', 'Computer Engineering'), ('math', 'Mathematics')], max_length=8)),
                ('university', models.CharField(choices=[('itu', 'Istanbul Technical University'), ('boun', 'Bogazici University'), ('koc', 'Koc University')], max_length=8)),
                ('number_of_previous_work_experience', models.IntegerField(default=0)),
                ('years_worked', models.IntegerField(default=0)),
                ('is_currently_employed', models.BooleanField(default=False)),
                ('skills_text', models.TextField(max_length=512)),
            ],
        ),
    ]
