# Generated by Django 3.1.5 on 2021-01-18 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='degree',
            field=models.CharField(choices=[('bsc', 'Bachelor of Science'), ('msc', 'Master of Science')], help_text='Degree', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='major',
            field=models.CharField(choices=[('cmpe', 'Computer Engineering'), ('math', 'Mathematics')], help_text='Major', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='university',
            field=models.CharField(choices=[('itu', 'Istanbul Technical University'), ('boun', 'Bogazici University'), ('koc', 'Koc University')], help_text='University', max_length=128, null=True),
        ),
    ]
